// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBox: typeof import('./components/ScoreBox.vue')['default']
    SelectedTrackDetails: typeof import('./components/SelectedTrackDetails.vue')['default']
    SkillBlock: typeof import('./components/SkillBlock.vue')['default']
  }
}
